const rankerDb = [
  { name: "tg_master99", score: "19.7B" },
  { name: "crypto_warrior", score: "17.1B" },
  { name: "blockchain_hero", score: "16.8B" },
  { name: "digital_specter", score: "16.3B" },
  { name: "bit_wolf88", score: "15.7B" },
  { name: "quantum_techx", score: "15.2B" },
  { name: "byte_luna404", score: "14.9B" },
  { name: "shadow_hawk09", score: "14.5B" },
  { name: "alpha_dev777", score: "14.1B" },
  { name: "omega_cyber13", score: "12.5B" },
  { name: "knight_byte22", score: "11.9B" },
  { name: "hyper_nova01", score: "11.4B" },
  { name: "vortex_neon66", score: "11B" },
  { name: "dark_storm333", score: "10.1B" },
  { name: "solar_flare10", score: "9.8B" },
  { name: "loop_infinity", score: "9.4B" },
  { name: "stellar_echo55", score: "9.2B" },
  { name: "tech_wizard90", score: "8.7B" },
  { name: "rider_void07", score: "8.5B" },
  { name: "astro_gamer12", score: "7.9B" },
  { name: "byte_crusherx", score: "7.6B" },
  { name: "cyber_dragon42", score: "7.2B" },
  { name: "phantom_dev69", score: "7.1B" },
  { name: "falcon_horizon23", score: "6.9B" },
  { name: "cobra_stealth88", score: "6.7B" },
  { name: "hunter_vortex77", score: "6.3B" },
  { name: "glitch_master909", score: "6.1B" },
  { name: "titan_byte555", score: "5.8B" },
  { name: "nova_ranger20", score: "5.5B" },
  { name: "shadow_echo303", score: "5.2B" }
];


export default rankerDb;